### PR TITLE
docs: add ADR-006 autocompletion

### PR DESCRIPTION
**Pull request by machow**
cc @tmastny in case you're interested, or want to weigh in! I tried to take everything we tried and cram it into an ADR, so I can cut down on digging around the IPython code base next time :).

https://nbviewer.jupyter.org/github/machow/siuba/blob/1d041cb16db591922933da21d5b0cf4338a57970/examples/architecture/006-autocompletion.ipynb

I think two big potential points it discusses are...

* Python's built-in ast library could be really useful for identifying DataFrames
* an approach to wrapping `_jedi_matches` that could save us from having to copy in the function's code

### CODE REVIEW

**Comment by tmastny** [comment]
Thanks for documenting this, it is really thorough. I went back through my notes and I don't think I have anything about the IPython classes or execution. 

I really like the new directions: the `ast` idea is interesting, and I think the new approach to `_jedi_matches` looks a lot better.

I think there's one additional method to consider for data frame inference. Parsing through `HistoryAccessor` (maybe the `ast` approach as well?) only looks at code that has already been executed. There has to be a way to avoid this: RStudio doesn't depend on a recent execution to find suggestions. It knows you are in a pipe chain, and as far as I can tell offers suggestions from the first object in that chain.

There has to be some class in IPython or ipykernel that gives more detailed information on the current input cell and cursor location. If we had that, we could try to figure out a way to look at the name at the start of the pipe:
```python
v = 1
other_df >>\
    mutate(....)

# ^ commands in input cell irrelevant to cursor/tab context

mtcars >>\
   filter(_.<TAB>
```

**Comment by machow** [comment]
> I think there's one additional method to consider for data frame inference. Parsing through HistoryAccessor (maybe the ast approach as well?) only looks at code that has already been executed. There has to be a way to avoid this

That's fair--I'll toss a note in in the section discussing parsing the full code. I think a big challenge there is that the code may  valid python syntax (or R in Rstudio's case), but if they got it to work reliably (e.g. using regex?), then maybe that's a good sign :). I'll note that AFAICT the IPython completer may be able to complete on a full block of text sometime in the future, so all the pieces would be there...

**Comment by tmastny** [comment]
RStudio uses regex. Here are their test cases for an incomplete pipe expression: https://github.com/rstudio/rstudio/blob/3fdda38e9a78a984a25c44e1672cf0869fad19cd/src/cpp/core/r_util/RTokenCursorTests.cpp#L75
```r
mtcars %>% first_level() %>% second_level(1
```

The regex is controlled by the [RTokenCursor](https://github.com/rstudio/rstudio/blob/78450b347e4f2b941c061fa1481ece6c1747a5ad/src/cpp/core/include/core/r_util/RTokenCursor.hpp#L40) class and the [getHeadOfPipeChain](https://github.com/rstudio/rstudio/blob/78450b347e4f2b941c061fa1481ece6c1747a5ad/src/cpp/core/include/core/r_util/RTokenCursor.hpp#L956) method.

I'd love to dive into something like this for IPython after my current project.

**Comment by machow** [comment]
Sorry, will merge this week 😬. I've been thinking a lot about / using the autocomplete, and have really come around to the regex approach you laid out. It seems like parsing history is nice because it's simple to parse, but seems way more useful to pull out the data from whatever code chunk is being worked on!

**Comment by machow** [comment]
oof--finally getting around to more siuba development! If you're interested in picking up more autocomplete work, or any other pieces of the library, happy to help out :)

**Pull request merged**
