### PR TITLE
[WIP] - Docs groupby internals

### PR DESCRIPTION
**Pull request by machow**
cc @has2k1, here's the write-up on groupby internals. Would be really interested to hear if there are any parts that could be clarified, or related areas you've thought of experimenting with for groupbys that might be useful to cover :).

Mermaid Diagrams don't work great in github's rendering. Here's a link to nbviewer

https://nbviewer.jupyter.org/github/machow/siuba/blob/docs-groupby-internals/examples/architecture/007-how-pandas-groupby-works.ipynb

### CODE REVIEW

**Comment by has2k1** [comment]
Thank, it reveals a good skeleton of the grouping process.

I am thinking about interrupting the groupby process to

1. Use numpy arrays of the groups in the computations.
2. Maybe create pseudo (light weight) dataframes for internal use to cut down on the overhead of the complete dataframes. e.g. a dict of numpy slices of arrays may involve no copying of data. But this too has limitations, e.g. you cannot do `x.pdfunc()` if `pdfunc` is a Series only function without a numpy mirror.

Currently in plydata, computing on grouped dataframes is essentially

```python
_results = []

for _, gdf in df.groupby('g'):
    # one or more evaluations that uses gdf
    gdf['new_column'] = 2 * gdf['original_column']
    _results.append(gdf)

result = pd.concat(_results)
```

The only change is that the evaluations are string based. This makes it versatile in that it can evaluate almost anything that makes sense in the split-apply-combine paradigm. But going all the way and creating group dataframes has a big performance overhead.

That is why, where possible and not too involved I want to interrupt the grouping process. Pandas does exactly this for [common functions](https://github.com/pandas-dev/pandas/blob/73c1d3269830d787c8990de8f02bf4279d2720ab/pandas/core/groupby/ops.py#L327-L347) and it a substitutes it's own [cython alternatives](https://github.com/pandas-dev/pandas/blob/73c1d3269830d787c8990de8f02bf4279d2720ab/pandas/_libs/groupby.pyx#L461) that work with numpy arrays and group indices.


```python
def my_mean(arr):
    return np.mean(arr)

mtcars.groupby('cyl').agg(np.mean)  # fast
mtcars.groupby('cyl').agg('mean')   # fast
mtcars.groupby('cyl').agg(my_mean)  # slow
```

I assume (I tried to look at the Siuba source but I quickly got overwhelmed), by carefully regrouping in between computations Siuba taps into these shortcuts used by Pandas.

**Comment by machow** [comment]
Hey, thanks for looking it over!

I can definitely see the appeal of using strings in plydata now, to avoid the whole "that outer function is calling a symbolic" issue.

> Pandas does exactly this for common functions and it a substitutes it's own cython alternatives that work with numpy arrays and group indices.

Yeah, this is exactly how siuba is optimizing. It is essentially a fancy wrapper around grouped DF methods to do three things

* representing the result of pandas aggregation methods with a new class, GroupByAgg.
* broadcasting GroupByAgg results when needed (e.g. subtracting the mean from a column)
* verifying that data can be broadcast or have identical groupers before operations

> That is why, where possible and not too involved I want to interrupt the grouping process.

Thinking about it more, none of the fast method tooling is tied to siuba, except at the final step of implementing mutate. For example, in this PR I've experimented with exposing the tools as the classes FastGroupedDataFrame, FastGroupedSeries--which avoids the need to use siuba's symbolic expressions and tree visitors.

At the extreme, it seems like the tooling or parts of it could be even pulled into its own library? Essentially with these files, that don't depend on siuba at all...

* spec.yml,.py - declaration of what kind of operation a pandas method is (e.g. elementwise vs aggregate, property or not, if it uses an accessor)
* translate.py - functions that operate on SeriesGroupBy or its subtype GroupByAgg
* groupby.py - implementation of GroupByAgg, glue functions to work around not being able to properly subclass SeriesGroupBy (AFAICT; may have changed in newer versions of pandas)
* create_grouped_methods dialect.py - combine spec.yml and translate.py into 1 function per method in the spec.

The parts are still a bit in flux right now, but if you're interested in using parts in plydata, I definitely don't mind experimenting with things. If it's helpful at all, [ADR-003](https://nbviewer.jupyter.org/github/machow/siuba/blob/master/examples/architecture/003-fast-mutate.ipynb) explains some rationale behind the architecture and has a self-contained example (that became groupby.py).

**Comment by machow** [comment]
OH, one challenge I forgot to add RE pandas using cython and the fast path is that AFAIK there's no optimized path for operations over 2 columns (like corr). It seems like an interesting quirk in pandas' design.

**Comment by machow** [comment]
Ah, finally got around to fixing some parts and merging. I did some testing of an OOP implementation that would allow it to just replace a DataFrameGroupBy, but allow expressions like `df.x - df.x.mean()`.

At some point, it could be interesting to pull into its own package, so libraries like plydata would have the option of using it for doing things like..

```
df.groupby('g').define(y = "x - x.mean()")
```

at the very least, just by setting the context variables to be the alternate SeriesGroupBy classes.

**Pull request merged**
