### PR TITLE
tab complete prototype

### PR DESCRIPTION
**Pull request by tmastny**
This PR is a prototype tab completer for #155. 

siuba-autocomplete

IPython is [designed](https://ipython.readthedocs.io/en/stable/config/integrating.html) to look for the [`__dir__`](https://docs.python.org/3/library/functions.html#dir) method on a Class to provide autocompletion. This is what [pandas](https://github.com/pandas-dev/pandas/pull/5050/files) uses for tab completion. 

The challenge for `Symbolic` is that it has no access to any dataframe attributes. That's the whole point of the class. So we need to do some lookup based on recent objects or context to provide tab completion. RStudio does this really well with column names in `%>%` chains, but I couldn't really figure out how.

My attempt uses IPython magics and history to find a suitable dataframe to borrow column names from. 

[`%who_ls`](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-who_ls) gives the name and class of the user defined objects in the IPython instance. I tried using something standard like `globals()`, but that only returns variables defined _within_ the module. Since `_.__dir__()` is called in `siu.py`, it doesn't have access to dataframes defined in the IPython session. A list is returned, and we filter for dataframe names in the session to pull columns from.

However, `%who_ls%` returns the names in alphabetic order which doesn't work well. Therefore, we need to look at the command history for relevant dataframes. I'm using the [`HistoryAccessor`](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.history.html#IPython.core.history.HistoryAccessor) class to look at the most recent commands. I'm searching for assignments, method calls, and imports in the commands that use the dataframe name, and return the latest one. I'm missing some basic cases like `[`, and it could probably be improved with some regex. 

There are also edge cases in the completion. For example, this doesn't return `mtcars` columns:
```python
import pandas as pd
from siuba import _
d = pd.DataFrame(dict(a=[1], b=[2]))
from siuba.data import mtcars
_.<TAB>
```
It's still prototype, but it seems to be working well in many basic cases, so I wanted to get your take on the approach.

### CODE REVIEW

**Comment by machow** [comment]
Ah thanks for looking into this! I'll take a closer look tomorrow, but decided to take the opportunity to dig a bit into how ipython does autocomplete, and wanted to leave some quick notes.

From what I understand, this is the sequence of things that happens..

* jedi's Terminal class is used for autocomplete
* It's called by IPython's [IPCompleter] (https://github.com/ipython/ipython/blob/d14c35c0d1d842f3286c2b33beb049291be09193/IPython/core/interactiveshell.py#L2137), which is called by the kernel ([here is where it's init'd](https://github.com/ipython/ipython/blob/d14c35c0d1d842f3286c2b33beb049291be09193/IPython/core/interactiveshell.py#L2137))
* ipykernel used to do completion via `shell.complete()`, but now directly [calls the "experimental" `shell.Completer._completions`](https://github.com/ipython/ipykernel/blob/f0b004010c606b19321b13386fccf0dcfd964c83/ipykernel/ipkernel.py#L384).

It looks like IPython shell has two ways to dispatch a custom code completion function...

```python
shell = get_ipython()

# Approach 1: this sets IPCompleter.custom_matches
# it just returns the suggestion z--<whatever text you had>
shell.set_custom_completer(lambda completer, text: ["z--%s" % text])

# Approach 2: this sets IPCompleter.custom_completers
# this will dispatch when the line being completed matches the regex below
def completer(shell, event):
    print('event:', event, '\n')
    return ['_.c']

shell.set_hook('complete_command', completer, re_key = '.*')
```

Testing using [code from ipykernel](https://github.com/ipython/ipykernel/blob/f0b004010c606b19321b13386fccf0dcfd964c83/ipykernel/ipkernel.py#L384):

```python
from IPython.core.completer import provisionalcompleter
with provisionalcompleter():
    print(list(shell.Completer._completions('  _.', 4, _timeout = 10000)))
```

Output:

```
event: namespace(command='_.', line='  _.', symbol='_.', text_until_cursor='  _.') 

[<Completion start=2 end=4 text='_.c' type='<unknown>', signature='?',>]
```

**Comment by tmastny** [comment]
I did some investigation on this approach. Based on my exploration in https://github.com/machow/siuba/pull/249, I'd want this method to also support `pandas.Series` tab completion because I think that's really useful.

The initial difficulty here was that the regex `'.*_.*'` matches on both `_.<TAB>` and `_.abc.<TAB>`. However, those need to be dispatched separately. I'm not the best at regex, but I found a solution that works in some basic cases, but not more complex ones. 

custom-complete


A couple of things to note about this method. It's much more generic than the object attribute completion. IPython uses it for various [module and magic](https://github.com/ipython/ipython/blob/d14c35c0d1d842f3286c2b33beb049291be09193/IPython/core/interactiveshell.py#L2161-L2166) completion methods, which means it has a different style of completion that includes the phrase in the suggestion. So `_.<TAB>` suggests `_.am` rather than `am` like in object attribute completion with `__dir__`. That interface is more unfamiliar when dealing with python objects and I personally prefer the object attribute style, but maybe there's a way to change that. 

##

Code:

```python
from siuba import *
from siuba.data import mtcars

## Approach 2 approach
from IPython.core.history import HistoryAccessor


# we can reuse the basically the same dataframe lookup functions
def match_df_name(dfs, commands):
    if not dfs:
        return []

    for command in reversed(commands):
        exact_match = [df for df in dfs if df in command]
        if exact_match:
            return exact_match[0]

        method_match = [df for df in dfs if df + "." in command]
        if method_match:
            return method_match[0]

        assign_match = [df for df in dfs if command.startswith(df + " = ")]
        if assign_match:
            return assign_match[0]

        import_match = [df for df in dfs if "import " + df in command]
        if import_match:
            return import_match[0]

        in_expression = [df for df in dfs if df + "," in command or df + ")" in command]
        if in_expression:
            return in_expression[0]

    return dfs[0]

def find_df_in_history(shell):
        dfs = shell.run_line_magic('who_ls', 'DataFrame')

        history = HistoryAccessor()
        commands = [command for _, _, command in history.get_tail(include_latest=True)]

        return match_df_name(dfs, commands)

def symbolic_completer(shell, event):
    
    df = find_df_in_history(shell)

    if not df:
        return []
    
    columns = list(shell.ev(df).columns)    

    # have to prefix commands to match
    return ["_." + column for column in columns]


shell = get_ipython()
shell.set_hook('complete_command', symbolic_completer, re_key = '.*\_\.([^a-zA-Z]|^\s|$)')

from pandas import Series

def series_completer(shell, event):

    # some additional complexity with this method. Private attributes `_` and `__` are
    # are not automatically suppressed. 
    methods = [method for method in dir(Series) if not method.startswith('_') and not method.startswith('__')]
    
    return [event.command + method for method in methods]

shell.set_hook('complete_command', series_completer, re_key = '.*\_\.[a-zA-Z]+\.(\,.*|\).*|\].*|$)')
```

**Comment by tmastny** [comment]
Interesting note about method 1 and method 2: method 2 has access to strictly more information than method 1. The following data is all sent to method 2, which is basically the same as the data send to the default completer method in `jedi`: 

https://github.com/ipython/ipython/blob/d14c35c0d1d842f3286c2b33beb049291be09193/IPython/core/completer.py#L1775-L1780

Method 1 on the other hand only gets the raw text, with the additional event data: 

https://github.com/ipython/ipython/blob/d14c35c0d1d842f3286c2b33beb049291be09193/IPython/core/completer.py#L2115-L2119

**Comment by machow** [comment]
Thanks for following up on it--this is incredible! What do you think of this?

* using the code you have for finding dataframes from history
* maybe using a very slightly modified version of Completer._jedi_matches in the hook (shown below)

It essentially swaps in the dataframe for the variable `_` when jedi is doing the autocomplete, so the results it gives back should be identical to autocompleting the dataframe direcly! The one caveat is that it the custom hook can get the type info that jupyter shows, but has to remove it for the hook to work :/.

| dataframe | siu |
| ---------- | --- |
|  image | image |


### How Jedi is run

```python
from siuba.data import mtcars
shell = get_ipython()

df_auto = list(shell.Completer._jedi_matches(7, 0, "mtcars."))

df_auto[:5]
```

```
[<Completion: abs>,
 <Completion: add>,
 <Completion: add_prefix>,
 <Completion: add_suffix>,
 <Completion: agg>]
```

```python
ser_auto = list(shell.Completer._jedi_matches(11, 0, "mtcars.mpg."))

# similar output as the df's autocomplete (but no column names)
ser_auto[:5]  
```


### Replacing `_` with the DataFrame when running Jedi

If you expand the details below, I just took the method `_jedi_matches` and turned it into a function with 1 line changed...

(copied from `from IPython.core.completer.IPCompleter._jedi_matches`...)

<details>

```python
from IPython.core.completer import cursor_to_position, _FakeJediCompletion
import jedi 

def _jedi_matches(self, cursor_column:int, cursor_line:int, text:str, df_name = "_"):
    """

    Return a list of :any:`jedi.api.Completions` object from a ``text`` and
    cursor position.

    Parameters
    ----------
    cursor_column : int
        column position of the cursor in ``text``, 0-indexed.
    cursor_line : int
        line position of the cursor in ``text``, 0-indexed
    text : str
        text to complete

    Debugging
    ---------

    If ``IPCompleter.debug`` is ``True`` may return a :any:`_FakeJediCompletion`
    object containing a string with the Jedi debug information attached.
    """
    # ----- ONLY CHANGED THE LINE BELOW RIGHT BELOW ------------
    #namespaces = [self.namespace]
    namespaces = [{**self.namespace, "_": self.namespace[df_name]}]
    if self.global_namespace is not None:
        namespaces.append(self.global_namespace)

    completion_filter = lambda x:x
    offset = cursor_to_position(text, cursor_line, cursor_column)
    # filter output if we are completing for object members
    if offset:
        pre = text[offset-1]
        if pre == '.':
            if self.omit__names == 2:
                completion_filter = lambda c:not c.name.startswith('_')
            elif self.omit__names == 1:
                completion_filter = lambda c:not (c.name.startswith('__') and c.name.endswith('__'))
            elif self.omit__names == 0:
                completion_filter = lambda x:x
            else:
                raise ValueError("Don't understand self.omit__names == {}".format(self.omit__names))

    interpreter = jedi.Interpreter(
        text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
    try_jedi = True

    try:
        # find the first token in the current tree -- if it is a ' or " then we are in a string
        completing_string = False
        try:
            first_child = next(c for c in interpreter._get_module().tree_node.children if hasattr(c, 'value'))
        except StopIteration:
            pass
        else:
            # note the value may be ', ", or it may also be ''' or """, or
            # in some cases, """what/you/typed..., but all of these are
            # strings.
            completing_string = len(first_child.value) > 0 and first_child.value[0] in {"'", '"'}

        # if we are in a string jedi is likely not the right candidate for
        # now. Skip it.
        try_jedi = not completing_string
    except Exception as e:
        # many of things can go wrong, we are using private API just don't crash.
        if self.debug:
            print("Error detecting if completing a non-finished string :", e, '|')

    if not try_jedi:
        return []
    try:
        return filter(completion_filter, interpreter.completions())
    except Exception as e:
        if self.debug:
            return [_FakeJediCompletion('Oops Jedi has crashed, please report a bug with the following:\n"""\n%s\ns"""' % (e))]
        else:
            return []
```

</details>

Then, 

```python
# Set hook ----

shell = get_ipython()

from siuba.siu import Symbolic

def swap_siu_completer(shell, event):
    df_name = "mtcars"    # or could get directly from shell.user_ns
    
    if isinstance(shell.user_ns.get("_"), Symbolic):
        completions = _jedi_matches(
            shell.Completer,
            len(event.symbol), 0, event.symbol,
            df_name = df_name
        )
        
        # necessary, since Completer assumes you'll return a list of strings back.
        # too bad, since the jedi completions are how jupyter gives more info
        # about completions to the user (like types, etc..)
        return [event.command + x.name for x in completions]
    return []


shell.set_hook('complete_command', swap_siu_completer, re_key = '.*')

# Test -----

from siuba.siu import _
from siuba.data import mtcars

# returns exact results as mtcars.<Tab>, but w/o the nicely colored boxes :/
_.<Tab>
```

### Alternatives

Could do something like...

```python
def hook(shell, event):
    # change the completers namespace, then change it back at the end
    # would likely need to be done in a context manager, down the road!

    old_ns = shell.Completer.namespace
    target_df = shell.user_ns["mtcars"]
    shell.Completer.namespace = {**old_ns, "_": target_df}

    # then, run completion method, not sure how...
    completions = shell.Completer.<some_method>(...)

    shell.Completer.namespace = old_ns
    
    return completions
```

**Comment by tmastny** [comment]
Finding the right `shell.Completer.<some_method>(...)` is a little awkward because custom completers are called in the middle of the standard completion method: https://github.com/ipython/ipython/blob/d14c35c0d1d842f3286c2b33beb049291be09193/IPython/core/completer.py#L2131

However, we can use the same trick you did before, by erasing old completers so we don't get stuck in an infinite loop:

https://github.com/machow/siuba/blob/3f5ac05c5cbf8c0300be203b3190900ae896dffc/siuba/completer.py#L4-L23

And I'm honestly not sure _why_ this works, but doing it this way also gives you the nice method coloring! 

best-completer-yet

Couple of `TODO`s on my end:
1. figure out _why_ I get the coloring on this method. I was too excited not to share right away
2. look into the context manager you suggested

The only downside to this approach is that for some reason you need to call `import siuba.completer`. I thought it should work when you call `from siuba import *`, but that doesn't seem to be the case. Any ideas there?

**Comment by machow** [comment]
This is incredible--I'm so confused about how the color is in there but that's wild :o. 

> I thought it should work when you call from siuba import *, but that doesn't seem to be the case. Any ideas there?

What do you think of us putting the code in `siuba/experimental/completer.py`? It seems like something that would be really cool to get out and test, while working out potential hitches that come up. It seems like we could merge with what you have + the DataFrame lookup code. I'll likely try to summarize some of the Completer things in an [architecture decision record](https://github.com/machow/siuba/tree/master/examples/architecture). If you do any blogging, the completer definitely seems like a pretty intriguing part of IPython :).

### Package dev housekeeping things (not important for now!)

There are few package dev things that it'll likely need eventually (not critical for merging as experimental, and I'm happy to help w/ any parts)...

* try/except on the IPython import (since it's not a siuba dependency; this would be critical if it were imported by default)
* some strategy around unanticipated completion errors
* some strategy around potential usability issues (e.g. are the cases where the time to look up a DataFrame affect user experience?)

**Comment by machow** [comment]
It looks like the reason it's not setting the hook with `from siuba import *` is because there'd need to be an import of the completer in `siuba/__init__.py`

**Comment by tmastny** [comment]
I think this is ready for an merge into `experimental`. You can activate the completer by running 
```py
import siuba.experimental.completer
```
in a ipython session.

Some other todos I'll be thinking about:
- [ ] add unit tests. 
`_match_df_name` could definitely benefit from some, but I'd like also to test end-to-end. Need to research how to run an ipython session from a python session. 

- [ ] investigate why this method gives color and attribute/method completion.
This is confusing, especially when the other methods don't offer that. 

Your suggested todos:
- [ ] try/except on the IPython import (since it's not a siuba dependency; this would be critical if it were imported by default)
It seems like there are a couple 

- [ ] some strategy around unanticipated completion errors
It seems like there are a few patterns here: [SO](https://stackoverflow.com/a/3496790/6637133), [pandas](https://github.com/takluyver/pandas/blob/6c820b4b1a3b945d52cffbd9a4d40a582c077b5d/pandas/core/frame.py#L4252-L4256). Not clear to me what the best approach is. Is there a Python convention like [Suggests](https://github.com/tmastny/sagemaker/blob/ec59fecf3d8eaeacc6433fdece4ccd294a64a949/DESCRIPTION#L18) for R packages?

- [ ] some strategy around potential usability issues (e.g. are the cases where the time to look up a DataFrame affect user experience?)
One place this could crop up in is this line:
https://github.com/machow/siuba/blob/531c8c4e5bd6c15793873dc351b4ff2a99aca165/siuba/experimental/completer.py#L65
By [default](https://ipython.readthedocs.io/en/stable/api/generated/IPython.core.history.html#IPython.core.history.HistoryAccessor.get_tail) this method only returns the last 10 commands. Is this enough? Not sure I have a good heuristic here

**Comment by tmastny** [comment]
One more thing popped up: sometimes errors are appearing in the IPython logs:
```
Traceback (most recent call last):
  File "/Users/Tim/python-package/siuba/siuba/experimental/completer.py", line 75, in symbolic_completer
    _, _, _, jedi = shell.Completer.complete(event.symbol)
ValueError: not enough values to unpack (expected 4, got 2)
```

It doesn't appear to crash the notebook, and everything seems to work after the error is thrown.

Do you consider this a blocker to merge into experimental? Either way I'm starting to look into it.

**Comment by tmastny** [comment]
## Bugs

It turns out the error I reported yesterday **was** the reason my method returned colored suggestions.

Here's what was happening. This was keyed in
```python
_.<TAB>
```
triggering `IPCompleter._complete` which eventually ran `dispatch_custom_completers` on line 2174, which then ran `symbolic_completer`. 


It then entered the context manager which swapped the namespaces:
https://github.com/machow/siuba/blob/97e5c90c088a1f17747e9e8789102d10ea0b5294/siuba/experimental/completer.py#L74-L75
However, as the error in my previous comment shows, it was failing on line 75.

Then why was I getting colored suggestions? It turns out I also had a bug in the exit handler:
https://github.com/machow/siuba/blob/97e5c90c088a1f17747e9e8789102d10ea0b5294/siuba/experimental/completer.py#L63-L67
Exit methods actually [need](https://alysivji.github.io/managing-resources-with-context-managers-pythonic.html) 4 arguments, not one: `def __exit__(self, exc_type, exc_value, exc_traceback):`. So it wasn't exiting properly, which means that  `shell.Completer.namespace` was never reset. So when we tried tab-completing the next time, the old namespace was still around, so it really thought it was completing `mtcars` because that's what `_` equaled in it's namespace.

## Next Attempt

The method you suggested in https://github.com/machow/siuba/pull/248#issuecomment-657330176 really works, but the downside is that you don't get the coloring. However, instead of setting a custom hook, we can override the jedi method directly: 
https://github.com/machow/siuba/blob/4f72b798e5334b8f4c8490fba2e8847ecb9a2344/siuba/experimental/completer.py#L133-L134

This gives us accurate, error-free tab-completing _with_ coloring. 

next-tab-complete-version

And while it's hacky (I especially don't like copy/pasting the method for only two lines of additional code), IPython has a page about modifying the shell and overwriting methods: https://ipython.readthedocs.io/en/stable/config/extensions/index.html

**Comment by machow** [comment]
Thanks again for all your work on this! I'm trying to wrap up a quick summary of key decisions / what we learned from the PR into an ADR, and will push to a branch in the next couple hours!

**Pull request merged**
